### ISSUE TITLE
Crash on empty file upload

### ISSUE THREAD

**Issue by Ezwal** [lennym/busboy-body-parser#21]
Using busboy and busboy-body-parser and node major version 7 and above, the application crash when dealing with an empty payload. The error thrown stems from the measure of the piped file buffer length ```Buffer.byteLength(d, 'binary')``` (index.js l.51). 
The major change to [Buffer](https://github.com/nodejs/node/pull/8946) break the module since d is an empty array it cause the error : 
```TypeError: "string" must be a string, Buffer, or ArrayBuffer```. Retrograding works since the line is working before #18

**Comment by lennym** [comment]
@Ezwal Thanks for opening this. I'll take a look asap.

**Comment by lennym** [comment]
@Ezwal ~Are you able to provide a minimal test case or steps to reproduce, ideally a curl command, that I can use to replicate this. I'm just trying to get an idea of what conditions would cause the payload to be empty, but still cause busboy to trigger a `file` event.~

~No problem if not, it'll just speed up the resolution if I don't have to reverse engineer it myself.~

Edit: It was easier than I expected.

**Comment by lennym** [comment]
Fix published at v0.3.1. Let me know if that solves your issues.

Thanks for your help.

**Comment by Ezwal** [comment]
it works fine now, thank you for the very quick response !
