### ISSUE TITLE
Crashes on invalid multipart data

### ISSUE THREAD

**Issue by HughePaul** [lennym/busboy-body-parser#4]
`dicer`, which is used by `busboy`, emits an error event on invalid end of multipart data. the `dicer` error is re-emmitted as a `busboy` error. As the busboy error event isn't listened to the `EventEmitter` throws this error causing server shutdown.

It looks like the `finish` event is also sent, so beware of double callbacks.

**Comment by lennym** [comment]
Fixed by #5
