### ISSUE TITLE
Add support for multiple files

### ISSUE THREAD

**Issue by JoeChapman** [lennym/busboy-body-parser#6]
I want to be able to upload multiple files in a single control

**Comment by lennym** [comment]
@JoeChapman There is the beginning of some work in this direction in #3 if you want to pick it up.

**Comment by easternbloc** [comment]
GIVEN I can muster the fucks
When I muster then fucks
THEN fucks will be mustered

**Comment by easternbloc** [comment]
Going forwards I'd really like this!

**Comment by lennym** [comment]
Published with `multi` support at 0.2.0
